import { esES } from "@clerk/localizations";
import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Inter, Outfit } from "next/font/google";
import Header from "../app/components/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const outfit = Outfit({subsets:["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider localization={esES}>
    <html lang="es">
      
      <body className={outfit.className}>
      <Header/>
        {children}</body>
    </html>
    </ClerkProvider>
  );
}
